# Project: MarranoFTP
# Makefile created by Dev-C++ 4.9.9.2

CPP  = i686-aros-g++.exe
CC   = i686-aros-gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"E:/amigadev/AmiDevCpp/usr/local/amiga/i686-aros/lib" ../CafLib/caflib.a ../../../usr/local/amiga/i686-aros/lib/libmui.a -o marranoftp   -s 
INCS =  -I"E:/amigadev/AmiDevCpp/usr/local/amiga/i686-aros/sys-include"  -I"E:/amigadev/AmiDevCpp/Sources"  -I"E:/amigadev/AmiDevCpp/Sources/AROS/CafLib/include" 
CXXINCS =  -I"E:/amigadev/AmiDevCpp/usr/local/amiga/lib/gcc-lib/i686-aros/3.3.1"  -I"E:/amigadev/AmiDevCpp/usr/local/amiga/i686-aros/sys-include"  -I"E:/amigadev/AmiDevCpp/Sources/AROS/CafLib/include" 
BIN  = MarranoFtp.exe
CXXFLAGS = $(CXXINCS)   -fexpensive-optimizations -O3
CFLAGS = $(INCS) -DCPU_LITTLE_ENDIAN -Wall   -fexpensive-optimizations -O3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before MarranoFtp.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "MarranoFtp.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
